spring:
  application:
    name: activity-reporter
  profiles:
    active: reporter
  webflux:
    base-path: "/reporter"
  datasource:
    host: ${database-host:localhost}
    port: ${database-port:1433}
    database: ${database-name:dummyName}
    username: ${database-user:dummyUser}
    password: ${database-password:dummyPassword}
  flyway:
    url: ${flyway-url:localhost}
    user: ${database-user:dummyUser}
    password: ${database-password:dummyPassword}
    enabled: true
  jpa:
    show-sql: true
  ai:
    openai:
      api-key: ${openai-api-key:dummyKey}
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.8
          max-completion-tokens: 4096
          timeout: 120s
          connect-timeout: 60s
          read-timeout: 120s


telegram:
  url: https://api.telegram.org
  lufa:
    token: ${telegram-token:dummyToken}
    chatId: ${telegram-chatId:dummyChatId}
  tre:
    token: ${telegram-token:dummyToken}
    chatId: ${telegram-chatId:dummyChatId}

discord:
  lufa:
    token: ${discord-token:dummyToken}
    channelId: ${discord-channelId:dummyChannelId}
  tre:
    token: ${discord-token:dummyToken}
    channelId: ${discord-channelId:dummyChannelId}

logging:
  level:
    cloud.cholewa: debug

---

spring:
  config:
    activate:
      on-profile: test
  flyway:
    enabled: false
